initial support for F77_CMAIN_FFLAGS

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -312,7 +312,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS NEMO NEMOHOST NEMO_LIBS NEMO_CFLAGS NEMO_FFLAGS WARNING NEMOVER build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP CXX CXXFLAGS ac_ct_CXX AWK INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA LN_S SET_MAKE RANLIB ac_ct_RANLIB X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS XLIBS XINCS GLLIBS F77 FFLAGS ac_ct_F77 FLIBS CCSHARED PGPLOT_DIR LOADOBJ_MACH LOADOBJ_LIBS MATH_LIBS HDF_INC HDF_LIB CFITSIO_INC CFITSIO_LIB PVM_LIB PVM_INC MIRIAD_INC MIRIAD_LIB GSL_CONFIG GSL_CFLAGS GSL_LIBS TCL_CFLAGS TCL_LIBS RDL_LIBS LIBOBJS YAPP_NAME YAPP_LIBS YAPP_DEF LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS NEMO NEMOHOST NEMO_LIBS NEMO_CFLAGS NEMO_FFLAGS WARNING NEMOVER build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP CXX CXXFLAGS ac_ct_CXX AWK INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA LN_S SET_MAKE RANLIB ac_ct_RANLIB X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS XLIBS XINCS GLLIBS F77 FFLAGS ac_ct_F77 FLIBS F77_CMAIN_FFLAGS CCSHARED PGPLOT_DIR LOADOBJ_MACH LOADOBJ_LIBS MATH_LIBS HDF_INC HDF_LIB CFITSIO_INC CFITSIO_LIB PVM_LIB PVM_INC MIRIAD_INC MIRIAD_LIB GSL_CONFIG GSL_CFLAGS GSL_LIBS TCL_CFLAGS TCL_LIBS RDL_LIBS LIBOBJS YAPP_NAME YAPP_LIBS YAPP_DEF LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -8452,6 +8452,116 @@ else
 echo "$as_me: WARNING: no FORTRAN compiler" >&2;}
 fi
 
+echo "$as_me:$LINENO: checking for f77 flags to use C main function" >&5
+echo $ECHO_N "checking for f77 flags to use C main function... $ECHO_C" >&6
+if test "${acx_cv_f77_cmain_fflags+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  acx_cv_f77_cmain_fflags="unknown"
+ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+cat >conftest.$ac_ext <<_ACEOF
+int main(void) { return 0; }
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  mv conftest.$ac_objext conftest_cmain.$ac_objext
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+acx_cv_f77_cmain_fflags=error
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+if test "x$acx_cv_f77_cmain_fflags" != xerror; then
+    ac_ext=f
+ac_compile='$F77 -c $FFLAGS conftest.$ac_ext >&5'
+ac_link='$F77 -o conftest$ac_exeext $FFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_f77_compiler_gnu
+
+    acx_save_LIBS=$LIBS
+    LIBS="conftest_cmain.$ac_objext $LIBS"
+    acx_save_FFLAGS=$FFLAGS
+    for acx_flag in none -nofor_main; do
+	case $acx_flag in
+	    none) FFLAGS=$acx_save_FFLAGS ;;
+	    *)    FFLAGS="$acx_save_FFLAGS $acx_flag" ;;
+	esac
+	cat >conftest.$ac_ext <<_ACEOF
+
+      subroutine foobar()
+      return
+      end
+
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  acx_cv_f77_cmain_fflags=$acx_flag; break
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext;
+    done
+    FFLAGS=$acx_save_FFLAGS
+    LIBS=$acx_save_LIBS
+    ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+fi
+fi
+echo "$as_me:$LINENO: result: $acx_cv_f77_cmain_fflags" >&5
+echo "${ECHO_T}$acx_cv_f77_cmain_fflags" >&6
+    case $acx_cv_f77_cmain_fflags in
+	error|unknown)
+	    F77_CMAIN_FFLAGS=""
+	    { echo "$as_me:$LINENO: WARNING: problems fortran-c interface" >&5
+echo "$as_me: WARNING: problems fortran-c interface" >&2;}
+	    ;;
+	*)
+	    if test "x$acx_cv_f77_cmain_fflags" = xnone; then
+		F77_CMAIN_FFLAGS=""
+	    else
+		F77_CMAIN_FFLAGS="$acx_cv_f77_cmain_fflags"
+	    fi
+
+	    ;;
+    esac
+
+
+
 if test "$GCC" = "yes"; then
   NEMO_CFLAGS="$NEMO_CFLAGS -rdynamic -fwritable-strings $gcov_flag"
 fi
@@ -8857,16 +8967,12 @@ else
   enable_gsltest=yes
 fi;
 
-  if test x$gsl_exec_prefix != x ; then
-     gsl_args="$gsl_args --exec-prefix=$gsl_exec_prefix"
-     if test x${GSL_CONFIG+set} != xset ; then
-        GSL_CONFIG=$gsl_exec_prefix/bin/gsl-config
+  if test "x${GSL_CONFIG+set}" != xset ; then
+     if test "x$gsl_prefix" != x ; then
+         GSL_CONFIG="$gsl_prefix/bin/gsl-config"
      fi
-  fi
-  if test x$gsl_prefix != x ; then
-     gsl_args="$gsl_args --prefix=$gsl_prefix"
-     if test x${GSL_CONFIG+set} != xset ; then
-        GSL_CONFIG=$gsl_prefix/bin/gsl-config
+     if test "x$gsl_exec_prefix" != x ; then
+        GSL_CONFIG="$gsl_exec_prefix/bin/gsl-config"
      fi
   fi
 
@@ -8917,22 +9023,22 @@ echo $ECHO_N "checking for GSL - version >= $min_gsl_version... $ECHO_C" >&6
   if test "$GSL_CONFIG" = "no" ; then
     no_gsl=yes
   else
-    GSL_CFLAGS=`$GSL_CONFIG $gslconf_args --cflags`
-    GSL_LIBS=`$GSL_CONFIG $gslconf_args --libs`
+    GSL_CFLAGS=`$GSL_CONFIG --cflags`
+    GSL_LIBS=`$GSL_CONFIG --libs`
 
-    gsl_major_version=`$GSL_CONFIG $gsl_args --version | \
+    gsl_major_version=`$GSL_CONFIG --version | \
            sed 's/^\([0-9]*\).*/\1/'`
     if test "x${gsl_major_version}" = "x" ; then
        gsl_major_version=0
     fi
 
-    gsl_minor_version=`$GSL_CONFIG $gsl_args --version | \
+    gsl_minor_version=`$GSL_CONFIG --version | \
            sed 's/^\([0-9]*\)\.\{0,1\}\([0-9]*\).*/\2/'`
     if test "x${gsl_minor_version}" = "x" ; then
        gsl_minor_version=0
     fi
 
-    gsl_micro_version=`$GSL_CONFIG $gsl_config_args --version | \
+    gsl_micro_version=`$GSL_CONFIG --version | \
            sed 's/^\([0-9]*\)\.\{0,1\}\([0-9]*\)\.\{0,1\}\([0-9]*\).*/\3/'`
     if test "x${gsl_micro_version}" = "x" ; then
        gsl_micro_version=0
@@ -13721,6 +13827,7 @@ s,@F77@,$F77,;t t
 s,@FFLAGS@,$FFLAGS,;t t
 s,@ac_ct_F77@,$ac_ct_F77,;t t
 s,@FLIBS@,$FLIBS,;t t
+s,@F77_CMAIN_FFLAGS@,$F77_CMAIN_FFLAGS,;t t
 s,@CCSHARED@,$CCSHARED,;t t
 s,@PGPLOT_DIR@,$PGPLOT_DIR,;t t
 s,@LOADOBJ_MACH@,$LOADOBJ_MACH,;t t
