Revised the proper nemobench

diff --git a/src/scripts/nemobench b/src/scripts/nemobench
--- a/src/scripts/nemobench
+++ b/src/scripts/nemobench
@@ -1,19 +1,22 @@
 #! /bin/bash
 #
 #   typically called via a Benchfile
-
+#set -x
 if [ $# -eq 0 ]; then
     echo Usage $0 cmd
     exit 0
 fi
 
+   
 log=/tmp/nemobench$$.log                 # per process
 log=/tmp/nemobench.log                   # global
 log=$XDG_RUNTIME_DIR/nemobench.log       # per session
-if [ ! -f "$1" ]; then
-    echo -n "NEMOBENCH: FAIL" >> $log
-    exit 0
-fi
+
+if ! command -v $1 >/dev/null 2>&1; then
+    echo -n "NEMOBENCH: FAIL"
+    echo ""
+    exit 1
+fi    
 echo NEMOBENCH: $* >> $log
 /usr/bin/time $* >> $log 2>&1
 echo -n "NEMOBENCH: $1 "
